language: node_js
node_js:
- '10'
script: npm run build

deploy:
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - "bin/node10-win-x64.tar.gz"
  - "bin/node10-macos-x64.tar.gz"
  on:
    tags: true
