language: node_js
node_js:
- '10'

before_install:
- sudo add-apt-repository ppa:duggan/bats -y
- sudo apt-get update -y
- sudo apt-get install bats jq -y

script: 
- npm run build
- npm link
- bats tests

deploy:
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.zip
  skip_cleanup: true
  on:
    tags: true
