language: node_js
node_js:
- '10'

os:
- windows
- osx
- linux

script: npm run build

matrix:
  allow_failures:
  - os: windows

deploy:
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.zip
  skip_cleanup: true
  on:
    tags: true
